<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Gerenciamento de Fontes</title>
    <link rel="stylesheet" type="text/css" href="view2.css" media="all">
    <link rel="icon" href="register.ico" type="image/x-icon" />
    <script type="text/javascript" src="fieldsRegister.js"></script>
    <script type="text/javascript" src="view.js"></script>
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript" src="registerValidate.js"></script>
</head>
<body id="main_body" onload="self.opener.location.reload();">
<img id="top" src="top.png" alt="">
<div id="form_container">
    <h1><a></a></h1>
    <form id="form_register" class="appnitro" autocomplete="off"  method="post" action="crud.php" >
        <div class="form_description">
            <h2 style="text-align: center">Gerenciamento de Fontes</h2>
            <p></p>
        </div>
        <ul >
            <li id="li_4" >
                <label class="description" for="element_4">Selecione uma opção </label>
                <div>
                    <select class="element select large" id="element_4" name="option_Register"  onchange="onSelect(this); blockRegisterFields(this)">
                        <option value="0">Selecione</option>
                        <option value="1" >Cadastrar fonte</option>
                        <option value="2" >Excluir fonte</option>
                        <option value="3" >Consultar fonte</option>
                    </select>
                </div>
                <p class="guidelines" id="guide_4"><span style="font-size: small;">Selecione uma opção.</span></p>
            </li>
            <li class="section_break">
                <h3></h3>
                <p></p>
            </li>
            <li id="li_3" style="display:none">
                <label class="description" for="element_4">Fontes de Pesquisa </label>
                <div>
                    <select class="element select large" id="sources" name="sources" title="" onchange="changeSources(this)">
                        <option value="0">Lista de Fontes</option>
                        <?php
                        error_reporting(E_ERROR | E_WARNING | E_PARSE);
                        require_once 'SourceManagement.php';
                        $a = new SourceManagement();
                        $a->addSource();
                        $a->deleteSource();
                        $a->listSources();
                        ?>
                    </select>
                </div>
                <p class="guidelines" id="guide_4"><span style="font-size: small;">As fontes cadastradas são armazenadas aqui.</span></p>
            </li>
            <li id="li_2" style="display:none">
                <label class="description" for="element_2">Fonte </label>
                <div>
                    <input id="url_name" name="url_name" class="element text medium" type="text" maxlength="255" value="" title=""/>
                </div>
                <p class="guidelines" id="guide_2"><span style="font-size: small;">Digite o nome da fonte de maneira simplificada.
                     Exemplo: "G1.com".</span>
                </p>
            </li>
            <li id="li_1" style="display:none">
                <label class="description" for="element_3">URL </label>
                <div>
                    <input id="url_register" name="url_register" class="element text large" type="text" maxlength="255" value="" title="" />
                </div>
                <p class="guidelines" id="guide_3"><span style="font-size: small;">Digite a url que deseja cadastrar.
                     Dica: busque o site de interesse, entre na página inicial e copie a url.</span>
                </p>
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="20269" />
                <input id="add" class="button_text" type="submit" name="add" value="Cadastrar" style="display:none"/>
                <input id="delete" class="button_text" type="submit" name="delete" value="Excluir" style="display:none"/>
            </li>
        </ul>
    </form>
    <br/>
    <div id="footer">
        Generated by <a href="mailto:pedro_artico@hotmail.com">P.A.R</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>