<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Exportação de Sentenças</title>
    <link rel="icon" href="check.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="view5.css" media="all">
    <script type="text/javascript" src="view.js"></script>
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript">
        self.opener.close();
    </script>
</head>
<body id="main_body"  style="background-color:#09ACDB" link= "#0000FF" alink= "#0000FF" vlink= "#0000FF">
<img id="top" src="top.png" alt="">
<div id="form_container">
    <h1 style="background-color:#4682B4"><a>Sentenças selecionadas</a></h1>
    <form id="form_22429" class="appnitro"  method="post" target="_blank" action="">
        <div class="form_description">
            <h2 style="text-align: center">Sentenças selecionadas</h2>
            <p></p>
        </div>
        <ul >
			<li>
                <label class="description">Após baixar o arquivo clique no botão <b style="color:blue">"Sair"</b>.</label>
			</li>	
				<a href="selected sentences.txt" download><p style="font-size:14px;">Clique aqui para baixar o arquivo com as sentenças selecionadas</p></a>
            <li id="li_1" >
                <label class="description" for="element_1"> </label>
                <div>
            </li>
            <input id='hide' type="text" name="hide" value="" title="" class="element text large" style="display:none"/>
            <li id="buttons" class="buttons">
            <input id="close" class="button_text" type="submit" name="close" value="Sair" formaction="selectedSentence.php"/>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="mailto:pedro_artico@hotmail.com">P.A.R</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>
               <?php
               require_once 'SentenceListWindow.php';	   
               $show = new SentenceListWindow();
			   $show->cleanTemporaryFiles();
               ?>